### ISSUE TITLE
KiDS Structural parameter: paper I revisions and submission

### ISSUE THREAD

**Issue by nrnapolita** [nrnapolita/KIWI_LSST#12]

**Comment by KiaraSpin** [comment]
GM 29/01
Nicola & Nyvia are working on the revisions. We need to understand the discrepancy between parameters inferred from different fitting methods (and therefore the disagreement between us and Kevin et al, 2017). Difficult to understand the real reason for this.  The only way would be to challenge the two routines on same set of data. We would like to avoid cause it is not just running GALFIT rather than 2DPHOT, but it is more following exactly the same steps followed by Kevin, which might be difficult to access and re-compute. 
Nicola has worked in understanding what has been done in the literature (e.g. different apertures, circularized vs not) 
Nyvia is working on the referee report.

**Comment by KiaraSpin** [comment]
GM 12/02
@nrnapolita is working on it.
1. Plot comparing literature results. A plot has been added to clarify the assumptions and definitions of sizes (e.g. circularized vs Major axis). Plotting apples vs apples makes  the comparison *much better*! We are consistent :)
2. We still have the problem 2DPHOT vs GALFIT. Systematic differences exist on 1-by-1 galaxies up to 50%

**Comment by KiaraSpin** [comment]
GM 26/02
@nrnapolita produced all the new figures and is in the phase of implementing the text changes.

**Comment by KiaraSpin** [comment]
GM 19/03
@nrnapolita will start working on it again this week. (Postponed due to travelling) 
Figures have been changed and revised according to ref comments.
AI @nrnapolita be ready with a new version of paper or at least the answer to the referee report by next Monday...

**Comment by KiaraSpin** [comment]
GM 16/04 
Nicola needs to hurry up with the revision (4 months already passed)

**Comment by KiaraSpin** [comment]
GM 21/05
Nicola started to work on the re-submission of the paper.
AI @nrnapolita CHECK THE DEADLINE for resubmission...and in case, write to the editor.

**Comment by KiaraSpin** [comment]
GM June 25 
The deadline for re-submission is 28 June. Nicola plans to provide a draft for co-authors tonight.

**Comment by KiaraSpin** [comment]
PAPER HAS BEEN SUBMITTED
