### ISSUE TITLE
UCMGs: future proposals

### ISSUE THREAD

**Issue by ctortora** [nrnapolita/KIWI_LSST#20]
It is time to think about UCMGs in a wider perspective.

In particular, It is time to start thinking and planning new proposals, to complete the sample of UCMGs with other new spectroscopic redshifts and to do deeper analysis, e.g. by measuring for subsamples better quality spectra for stellar population analysis:
(TNG deadline is passed, INT and WHT is still far).  

1.  **Future plans about the use of DOLORES@TNG**

2. **Future plans on 8-10m facilities**. Since we have enough spectra to study systematics in number counts, it should be nice to start selecting some of the validated UCMGs, e.g. with particular characteristics (e.g. very small, with Re< 1 kpc) and plan higher-resolution observations with GTC or VLT, to study stellar populations: In particular ages which give the definitive word about the origin of our selected UCMGs. And, of course, we can try to understand more about othe properties, as e.g. IMF!
For instance:
 - GRANTECAN. Trujillo can help (semester 2019A) 
 - VLT (for period 103). This should help to populate UCMG population around z = 0.5, but also to measure using less observing time brighter UCMG candidates.

3. **HST** for the same galaxies, to have better resolution for the fit of structural parameters. 
This should be discussed accurately, since to have a proposal accepted from HST is very difficult. It is an ambitious project.

**Comment by KiaraSpin** [comment]
GM 18 June
Together with Lucia Marchetti, we can submit a proposal to SALT. 
@ctortora  will lead the proposal. A companion proposal on lenses will be lead by Lucia.

**Comment by KiaraSpin** [comment]
GM 02/07
Crescenzo sent an email to collaborators with a plan for the two SALT proposals (UCMGs and Lenses).
 
- Ultra-compact galaxies (UCMGs). 
We can start with 15-30 UCMGs, let's see later how much time we need to obtain reasonable S/N for redshifts (and see also if we can measure the velocity dispersion). We can also observe lenses in the equatorial strip, thus we could potentially spread the observations across the whole year. Now we have the second paper out, with spectroscopic redshifts measured, we can demonstrate to be able to do it. I can prepare the proposal, starting with the previous ones as basis and updating them with the recent results.

- Gravitational lenses. 
We can start with something like 15-20 lenses. 
The idea is to observe a wide range of gravitational lenses, in order to pursue the "Gotta catch 'Em All" aim, so joining samples of lensed quasars (see her paper) and arcs/rings (found from CNN of Enrico). 
Of course, we need to tune the rationale of the proposal. Crescenzo and Chiara will discs about this, and we will produce a proposal (starting from the previous ones already submitted).  

@ctortora needs to talk to Lucia asap. 
- Which is the observation period? 
- Who leads the proposals? Do we have people from South Africa? would this increase the chances to get time? 
- LENSING: Should we go for a pilot program or do we aim for the whole sample? 

After that we can have a group discussion.

**Comment by KiaraSpin** [comment]
GM 02/07
HST Archival Data
@gdago queried the HST Archive and found out that some candidates have been observed with HST. 
He must however check one-by-one the images (there is no catalog for HST). It takes time.

**Comment by KiaraSpin** [comment]
GM 09/07 
We will focus for this SALT run on gravitational lenses.
It is in fact crucial to have people from South Africa and they are interested in lensing but not in UCMGs.

**Comment by KiaraSpin** [comment]
PROPOSAL HAS BEEN SUBMITTED. Fingers crossed now

**Comment by KiaraSpin** [comment]
GM 15/10 
This ISSUE has been closed. The discussion continues in #22
