### ISSUE TITLE
GAMA velocity dispersion: number checks

### ISSUE THREAD

**Issue by nrnapolita** [nrnapolita/KIWI_LSST#6]
AIs for GDA
1) luminosity completeness
2) mass completeness
3) match with DR3
4) match with DR4 as soon as possible

**Comment by gdago** [comment]
![r-lum_completeness_gama_kids](https://user-images.githubusercontent.com/22191556/33266934-c5d89de4-d377-11e7-8746-3602d9f601dd.png)
![schermata 2017-11-27 alle 12 01 35](https://user-images.githubusercontent.com/22191556/33266936-c90aa5b6-d377-11e7-8d8c-c2acaa95d800.png)
![completeness_gama_ppxfsample](https://user-images.githubusercontent.com/22191556/33266950-d3c18826-d377-11e7-9df1-3fd2365cae79.png)

**Comment by nrnapolita** [comment]
the plot on the top is the ratio between the GAMA_disperson sample vs. KiDS, how about GAMA_tot? It seems from the bottom panel that most of the galaxy mising at the low-z bin are small mass galaxies (hence small dispersion) which means that these might have been missed by ppxf

**Comment by nrnapolita** [comment]
GDA: 
match with DR3 has bee done: 22k out of 33k for which v.disp has been measured. As soon as we have the final catalog with 2Dphot parameter, we need to incorporate these value.

A.I.: for the final match witg KiDS DR3, we need to wait for the final DR3 structural parameters (see issue #1 )

**Comment by KiaraSpin** [comment]
GM 18/12: see issue#1  now we have more than 50000 vel disp measured.

**Comment by gdago** [comment]
Why completeness have a weird shape? 
In the three GAMA pointings (G9, G12, G15) we have different limiting magnitudes.
Only for G15:  19.8 mag. 
The final plot show the combination of the three pointings. 
In the plots, the dashed line represents completeness of velocity dispersion catalog. 

@ctortora Why do we have negative values? It has to do with the normalization with the area. We can easily ignore these points and cut the plot at zero.

**Comment by gdago** [comment]
@gdago Is this issue with completeness affecting the Faber-Jackson relation? 
G15 -> limited magnitude
GAMA -> all of them 

Result: There is an evolution with redshift, in the sense that for higher redshift the relation becomes flatter. 
The plots are showed in r and g bands
However, we do not agree with the literature. There is a tilt.
@ctortora Check the aperture within which the velocity dispersion is measured
@nrnapolita Also, why the two bands plots intercepting each other (us vs literature) in different points (in the two bands). Check the velocity dispersion definition!

**Comment by KiaraSpin** [comment]
Group Meeting 15/01/18
Paper preparation: catalog presentation + velocity dispersion measurements + these plots + discussion. 
TO BE DONE 
AI Peppe: Check consistency with literature. 
Also compare with other results (e.g. Hide and Bernardi 09 )

**Comment by KiaraSpin** [comment]
GM 29/01
@gdago is working on the draft.
AI group-> Peppe needs literature and papers on an explicit fit of the Faber-Jackson 
@ctortora  found something. He will share the link 

ATTENTION: The plots on this page are NOT up-to-date. The tilt is now gone

**Comment by ctortora** [comment]
GM 29/01
@gdago 

- [Here ](https://watermark.silverchair.com/mnras0394-1978.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAdgwggHUBgkqhkiG9w0BBwagggHFMIIBwQIBADCCAboGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMvCHQzYgqbQ-NrNXAgEQgIIBi6xCSOdUkIl8wNI3aDomI3FJqrP2qOLbGGgdR7ClFU_OEZeb-0Wn8MeIt38Hh5HPnrPO3cNoqpcKDq3lSO08Izcz4jRl6TSGQLgyPyAOnLw3sdfvOimkCnvx2zXwk1gRBuqba7mu7TvMCjadFcYoRYtafoXh7-AZB-iiWQNd1ANCgir_rrNGIjdWwj78tbkMzyg9VyIkHfnWUwJixiRxdatb7UcMHTOH1EWJ225gx05QDjRI_84zx6HkKxPyOe2tUSwtg5SySBwlK9_Fur_7BymqvVhy-x6CxLY-dW96uMv7mlTu02hZ8CSJsUdujQCtDBwqJF51ieirubX03-v7xbUW8GTH1E4GAIY_LzoOqpI61VjKJDpzmtMBTqlSIMJ0AZYzIMjaRtcExHFfOooViJcsZm14Qnz8rWdb4M9j9ozag0wSxb2_RoRXiTFwowkEBGxSRO3fJ0gy-yJ54YqA-zPgIAaRR-neBrkWa1DWp8iaNGW4NlasLybZAjL1-z-6ODK98dff6ZLgdIJf)you find the sigma-Mstar and sigma-mag correlation. "V" in table 1 is "log sigma", it is defined at the beginning of Sec. 3.

- I can also give you results from SPIDER (z<0.1) and from KiDS (z < 0.5-0.7). I have these data (I analyzed them in different papers). So, we can also overplot on your data these ones. We can chat about this.

**Comment by gdago** [comment]
![gama_dr3_master0_bernardir_band_corr](https://user-images.githubusercontent.com/22191556/36095292-dd89f21a-0ff1-11e8-9771-78529fd689dd.png)

**Comment by gdago** [comment]
![gama_dr3_master0_bernardir_band_corr](https://user-images.githubusercontent.com/22191556/36095321-08662ce2-0ff2-11e8-8c99-75334a111256.png)

**Comment by KiaraSpin** [comment]
GM 12/02
AI @gdago : 
- Check with other literature papers 
- In the next days analysis on a more complete sample will be finished; Giuseppe and Nicola are now full GAMA members. These products will be released to the internal survey. In exchange we got more data (internal release)

**Comment by KiaraSpin** [comment]
GM 26/02
@gdago found a little bug in the code. This could cause an increase in the final number of galaxy for which the dispersion can be measured.

**Comment by KiaraSpin** [comment]
GM 16/04

@gdago is working on getting results on the **full** GAMA catalog.

@ctortora would like to use the catalog with stellar masses, struc. par., velocity and velocity dispersions, etc to produce dark matter fraction (140000 galaxies)
**AI @gdago** send the catalog to Crescenzo.

**Comment by gdago** [comment]
GM 14/05 
@gdago  will send the catalog to @ctortora  today
and he will work on the paper.

**Comment by gdago** [comment]
![dago_hb_z035](https://user-images.githubusercontent.com/22191556/40306637-b913a600-5cff-11e8-9a1b-4aa4d80df154.png)
![dago_nn_z008_004](https://user-images.githubusercontent.com/22191556/40306640-bca979ca-5cff-11e8-9663-a0c59d988887.png)
![dago_nn_z001_035_hb_035](https://user-images.githubusercontent.com/22191556/40306643-be4bc634-5cff-11e8-941f-73bf9a0fdfa8.png)

**Comment by gdago** [comment]
The presentation will be focussed on the main results on the automatic internal kinematic extraction from the full GAMA private database "GAMAv27".

- >**150k velocity dispersions** have been retrieved with a **qFit>0.9** (which I defined to be a good fit threshold);

- >**120k velocity dispersions** have been retrieved with a **qFit>0.9 and SNR>3** (even low, such snr threshold still shows good agreement with SDSS vdisp catalogue, as shown in the first plot)

I can plot different relations, like FJ, which shows very good agreement with Hyde and Bernardi (**after a proper correction to the SDSS photometry**) and this is shown in the second plot. Still in the plot, we can see how by adding to the sample galaxies with z>0.35, the slope of the fit decreases, as usually expected.
We notice that the orange points (showing the same z-range investigated by HB) have been fitted in the completeness magnitude range for that redshift range (blue line in the third plot), as it's been computed that below ~-21.75 we suffer incompleteness effect.
This is obviously less a problem for z>0.35, since we are complete to brighter galaxies. Additionally, we need to notice that HB anyway found that the FJ-relation suffers a curvature at brighter magnitudes.

First of all, I will present the GAMA database, and the match with the KiDS tiles. Then, I will show the method I used for measuring the velocity dispersions and I will present the catalogue.
The rest of the presentation will show the comparison with SDSS and simulations in order to assess the robustness of the measurements, then I will end with FJ relation compared to the literature and in the end I will show how we can use my catalogue in synergy with KiDS.

I would like to draw the attention to the overlap between GAMA fields and KiDS (i.e. G09,G12,G15,G23), since the velocity dispersion catalogue I produced has an unprecedented amount of measurements which are not present in any of the present catalogues. By matching GAMA and KiDS catalogues (and, in case, by using also SDSS photometry or structural parameters) I can produce diagrams showing the relation between dynamical masses and stellar masses. I would like to interact with @ctortora in the next days in order to understand how to better improve the point that with my measurements we can investigate dark matter fractions in KiDS.

![sdss_gama_comparison_veldisp_multi8](https://user-images.githubusercontent.com/22191556/40613260-22ce42ca-627e-11e8-9c9e-65c87181b1df.png)
Plot 1: This shows the comparison with the SDSS DR14 database at different SNR thresholds. The green shadow shows relative scatter of 30%, while the blue dots and shadows indicate the median relative scatter and corresponding standard deviation.

![fj_hb_dago](https://user-images.githubusercontent.com/22191556/40613357-845d4f68-627e-11e8-8c93-f2ad223f506d.png)
Plot 2: This shows the comparison with HB 2009. The orange fit is in very good agreement with the literature (z<0.35). By adding galaxies with z>0.35, we notice that the fit to the data is less steeper, as expected. We don't show fit to data for redshift range up to z=0.15, or z=0.25, since we can notice from Plot 3 that we would suffer of severe incompleteness effects.

![absmag_appmag](https://user-images.githubusercontent.com/22191556/40613516-15bdb006-627f-11e8-8742-ac9d02a3d91a.png)
Plot 3: Absolute magnitudes versus apparent magnitude. This the absolute magnitude range we cover within the GAMA completeness range (17.7-19.8 r-mag), and the cuts we have when considering different redshift ranges.

Additional plots: the redshift distribution of the GAMA velocity dispersion sample and the SDSS matching with the full GAMA database.
![gama_sdss_z](https://user-images.githubusercontent.com/22191556/40613830-72c1a180-6280-11e8-8a71-0aef69a6736c.png)
![gama_sdss_z_cumulative](https://user-images.githubusercontent.com/22191556/40613835-775179a0-6280-11e8-8f9a-1972af776c2e.png)

**Comment by nrnapolita** [comment]
In Fig. 2 I don't understand in which direction the incomplteness at -21.75 works. I expected the consistency with HB to be present more at bright M<-21.73 luminosity, but there is where we see the bending of the slope and the deviation from HB. On the other hand at fainter mag everything is consistent.
Furthermore, we don't see any evolution with z, do we?

**Comment by nrnapolita** [comment]
Plot 2: "We don't show fit to data for redshift range up to z=0.15, or z=0.25, since we can notice from Plot 3 that we would suffer of severe incompleteness effects."
I don't understand as the low-z sample has a higher depth and then the incompleteness should raise at lower luminosities (e.g. M~-19.8 for z=0.15), or there is some incompleteness I don't see?
